on: 
  push:
    branches: [main]
    paths:
      - 'api/conversations.json'
      - 'api/books.json'
      - 'img/**'

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'main'
        path: 'main'

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: 'gh-pages'

    - name: Copy updated docs to gh-pages branch
      run: |
        mkdir -p gh-pages/img/book
        mkdir -p gh-pages/img/creature
        mkdir -p gh-pages/img/spell
        mkdir -p gh-pages/api/tree
        cp main/api/npc_data.json gh-pages/api/
        cp main/api/books.json gh-pages/api/
        cp main/img/npc/* gh-pages/img/npc/
        cp main/img/book/* gh-pages/img/book/
        cp main/img/creature/* gh-pages/img/creature/
        cp main/img/spell/* gh-pages/img/spell/
        cp main/api/conversations.json gh-pages/api/
        cp main/api/file_mapping.json gh-pages/api/
        cp main/doc/*_transcripts.md gh-pages/api/tree/
        cp main/api/npc_data.json gh-pages/api/
        cp main/api/books-img.json gh-pages/api/
        cp main/api/books.json gh-pages/api/
        cp main/img/npc/* gh-pages/img/npc/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './gh-pages'
        publish_branch: gh-pages
        commit_message: "Deployed to GitHub Pages by GitHub Actions"
        