name: NPC Workflow

on:
  pull_request:
    branches: [main]
    paths:
      - 'npc/**'
      - '!npc/conversations.json'
  push:
    branches: [main]
    paths:
      - 'npc/**'
      - '!npc/conversations.json'

jobs:
  validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Validate changes
        run: |
          cd npc
          python ../src/validate.py

  convert_and_publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Convert Markdown files to JSON
      run: |
        cd npc
        python ../src/md_to_json.py

    - name: Commit and push changes to GitHub Pages
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "GitHub Actions"
        author_email: "actions@github.com"
        message: "Update conversations.json"
        add: "npc/conversations.json"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes to GitHub Pages
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
